### ISSUE TITLE
Build with mqtt-client?

### ISSUE THREAD

**Issue by stephenmetzger** [kevineye/docker-shairport-sync#10]
Any way to build SPS with mqtt using this? can't get any of the additional commands that I've tried to work.

**Comment by kevineye** [comment]
My docker image (kevineye/shairport-sync) is very old; hasn't been updated in over four years. It looks like the MQTT features of shairport-sync (and I'm sure many more) have been added since then. You should try the official mikebrady/shairport-sync docker image instead -- https://hub.docker.com/r/mikebrady/shairport-sync
